-- =============================================================================
-- 00024 — Seed a broad country list (§35). Inactive by default: `active`
-- still gates which markets can CREATE requirements; property submissions may
-- reference any country. Admin can activate/configure markets in the console.
-- =============================================================================

insert into public.countries (code, name, active, default_language, supported_languages, default_currency, measurement_unit)
values
  ('SG','Singapore',false,'en','{en}','SGD','sqft'),
  ('TH','Thailand',false,'en','{en}','USD','sqm'),
  ('VN','Vietnam',false,'en','{en}','USD','sqm'),
  ('PH','Philippines',false,'en','{en}','USD','sqm'),
  ('KH','Cambodia',false,'en','{en}','USD','sqm'),
  ('MM','Myanmar',false,'en','{en}','USD','sqm'),
  ('BN','Brunei',false,'en','{en}','USD','sqft'),
  ('LA','Laos',false,'en','{en}','USD','sqm'),
  ('CN','China',false,'en','{en}','USD','sqm'),
  ('HK','Hong Kong',false,'en','{en}','USD','sqft'),
  ('MO','Macau',false,'en','{en}','USD','sqft'),
  ('TW','Taiwan',false,'en','{en}','USD','sqm'),
  ('JP','Japan',false,'en','{en}','USD','sqm'),
  ('KR','South Korea',false,'en','{en}','USD','sqm'),
  ('IN','India',false,'en','{en}','USD','sqft'),
  ('PK','Pakistan',false,'en','{en}','USD','sqft'),
  ('BD','Bangladesh',false,'en','{en}','USD','sqft'),
  ('LK','Sri Lanka',false,'en','{en}','USD','sqft'),
  ('NP','Nepal',false,'en','{en}','USD','sqft'),
  ('MV','Maldives',false,'en','{en}','USD','sqm'),
  ('SA','Saudi Arabia',false,'en','{en}','USD','sqm'),
  ('QA','Qatar',false,'en','{en}','USD','sqm'),
  ('KW','Kuwait',false,'en','{en}','USD','sqm'),
  ('BH','Bahrain',false,'en','{en}','USD','sqm'),
  ('OM','Oman',false,'en','{en}','USD','sqm'),
  ('JO','Jordan',false,'en','{en}','USD','sqm'),
  ('LB','Lebanon',false,'en','{en}','USD','sqm'),
  ('IL','Israel',false,'en','{en}','USD','sqm'),
  ('EG','Egypt',false,'en','{en}','USD','sqm'),
  ('TR','Turkey',false,'en','{en}','USD','sqm'),
  ('GB','United Kingdom',false,'en','{en}','USD','sqft'),
  ('US','United States',false,'en','{en}','USD','sqft'),
  ('CA','Canada',false,'en','{en}','USD','sqft'),
  ('AU','Australia',false,'en','{en}','USD','sqm'),
  ('NZ','New Zealand',false,'en','{en}','USD','sqm'),
  ('DE','Germany',false,'en','{en}','USD','sqm'),
  ('FR','France',false,'en','{en}','USD','sqm'),
  ('NL','Netherlands',false,'en','{en}','USD','sqm'),
  ('CH','Switzerland',false,'en','{en}','USD','sqm'),
  ('IT','Italy',false,'en','{en}','USD','sqm'),
  ('ES','Spain',false,'en','{en}','USD','sqm'),
  ('PT','Portugal',false,'en','{en}','USD','sqm'),
  ('SE','Sweden',false,'en','{en}','USD','sqm'),
  ('NO','Norway',false,'en','{en}','USD','sqm'),
  ('DK','Denmark',false,'en','{en}','USD','sqm'),
  ('FI','Finland',false,'en','{en}','USD','sqm'),
  ('IE','Ireland',false,'en','{en}','USD','sqm'),
  ('BE','Belgium',false,'en','{en}','USD','sqm'),
  ('AT','Austria',false,'en','{en}','USD','sqm'),
  ('GR','Greece',false,'en','{en}','USD','sqm'),
  ('PL','Poland',false,'en','{en}','USD','sqm'),
  ('CZ','Czechia',false,'en','{en}','USD','sqm'),
  ('HU','Hungary',false,'en','{en}','USD','sqm'),
  ('RO','Romania',false,'en','{en}','USD','sqm'),
  ('RU','Russia',false,'en','{en}','USD','sqm'),
  ('UA','Ukraine',false,'en','{en}','USD','sqm'),
  ('ZA','South Africa',false,'en','{en}','USD','sqm'),
  ('NG','Nigeria',false,'en','{en}','USD','sqm'),
  ('KE','Kenya',false,'en','{en}','USD','sqm'),
  ('MA','Morocco',false,'en','{en}','USD','sqm'),
  ('TN','Tunisia',false,'en','{en}','USD','sqm'),
  ('BR','Brazil',false,'en','{en}','USD','sqm'),
  ('MX','Mexico',false,'en','{en}','USD','sqm'),
  ('AR','Argentina',false,'en','{en}','USD','sqm'),
  ('CL','Chile',false,'en','{en}','USD','sqm'),
  ('CO','Colombia',false,'en','{en}','USD','sqm'),
  ('PE','Peru',false,'en','{en}','USD','sqm')
on conflict (code) do nothing;
